sequenceDiagram

 %% convert to png at: https://mermaid-js.github.io/mermaid-live-editor/

    participant AD as Auditor
    participant BC as Blockchain
    participant A as Authority
    participant T as Trustee
    participant R as Registrar
    participant V as Voter

    Note over BC,V: Setup Phase

    A->>A: Initial Election Parameters
    A->>+T: Send Params
    T-->>-A: Send Keys, Exponents, Proofs,<br/>Signatures as required for setup
    A->>+R: Send Params
    R-->>-A: Send RegURL, Keys and Signature<br />as required for setup

    A-->>+BC: Create Genesis Block
    BC-->+AD: Auditor Watches Chain

    Note over BC, V: Parameter Confirmation (Shares, then Public)

    BC->>+T: Check BlockChain for setup data
    T-->>-BC: Confirm with Signature and Encrypted Shares
    BC->>+R: Check BlockChain for all shares
    R-->>-BC: Confirm with Signature and Public Key Shard

    Note over BC,V: Voter Registration Phase

    BC->>+V: Check Genesis Block and Parameter Confirmation
    V->>+R: Authenticate with Registrar<br />and send Public Key
    R-->>-V: Sign PublicKey and VoterId
    V-->>-BC: Sign and Add Block with <br />Signed PublicKey and VoterId

    Note over BC,V: Vote Casting Phase

    V->>BC: Add Block with Signature, Encrypted <br />Votes and ZKP

    Note over BC,V: Tally Decryption Phase

    BC->>T: Calculate homomorphic sum of votes
    T->>BC: Add Block with Sum, PartialDecryption<br />and ZKP of correct decryption

    Note over BC,V: Audit Phase

    BC->>AD: Collect Partial Decryptions<br />Combine and Calculate<br />final result.